# Versión de la especificación de Docker Compose
version: "3.8"

services:

  # Servicio de Aplicación (API Backend)
  backend:

    # Indica que debe construir la imagen usando el Dockerfile local
    build: .

    # Nombre del contenedor para facilitar la identificación y logs
    container_name: tienda-backend

    # Variables de entorno para la integración con la base de datos
    environment:
      - DB_HOST=db              # Se usa el nombre del servicio como host
      - DB_USER=root
      - DB_PASSWORD=admin123
      - DB_NAME=tienda_perritos

    # Mapeo de puertos para exponer la API en el host 
    ports:
      - "3001:3001"

    # Indica que el servicio de backend depende del servicio de base de datos
    depends_on:
      - db

  # Servicio de Base de Datos (MySQL)
  db:

    # Uso de imagen oficial de MySQL versión 8
    image: mysql:8
    container_name: tienda-db

    # Configuración inicial de la base de datos
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=tienda_perritos

    # Mapeo del puerto estándar de MySQL
    ports:
      - "3306:3306"

    # Implementación de persistencia de datos
    volumes:

      # Volume para asegurar que la información no se pierda al reiniciar
      - dbdata:/var/lib/mysql

# Definición de volúmenes globales
volumes:

  # Volume gestionado por Docker para la continuidad operativa del sistema
  dbdata: