name: CI Pipeline - Backend Tienda Perritos

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    name: Construir y Subir a Amazon ECR
    runs-on: ubuntu-latest

    steps:
    - name: 1. Descargar el código
      uses: actions/checkout@v4 

    - name: 2. Configurar credenciales seguras de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1 

    - name: 3. Iniciar sesión en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: 4. Construir y publicar imagen Docker
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: tienda-backend
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: 5. Desplegar en servidor (CD)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_PRIVATE_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        proxy_host: ${{ secrets.BASTION_HOST }}
        proxy_username: ${{ secrets.EC2_USER }}
        proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Login en ECR desde la instancia
          aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
          
          mkdir -p ~/backend && cd ~/backend

          # Creamos el compose en el servidor usando la imagen de ECR en vez de 'build: .'
          cat << 'EOF' > docker-compose.yml
          version: "3.8"
          services:
            backend:
              image: ${{ steps.login-ecr.outputs.registry }}/tienda-backend:latest
              container_name: tienda-backend
              environment:
                - DB_HOST=db
                - DB_USER=root
                - DB_PASSWORD=admin123
                - DB_NAME=tienda_perritos
              ports:
                - "3001:3001"
              depends_on:
                - db
            db:
              image: mysql:8
              container_name: tienda-db
              environment:
                - MYSQL_ROOT_PASSWORD=admin123
                - MYSQL_DATABASE=tienda_perritos
              ports:
                - "3306:3306"
              volumes:
                - dbdata:/var/lib/mysql
          volumes:
            dbdata:
          EOF

          sudo docker compose pull
          sudo docker compose up -d